### ISSUE TITLE
Help, Please

### ISSUE THREAD

**Issue by jk3171** [ishaan26/Hackintosh_Acer-Predator-Helios-300_G-572#2]
Hello @ishaan26, 
I am quite new to Hackintoshing, and I was hoping you could help me. I have the same laptop as you, and I wish to Hackintosh it; except mine is the same as the other person (from the other issue on the repo) which is slightly different. My Predator is equipped with an i7-7700HQ, 16GB DDR4, GTX 1060 6GB, and I added a 2TB SSD (which will be for macOS).

Can you be as kind as to give me a walkthrough as how to accomplish Hackintoshing on this laptop, or maybe add the info to the Readme.md so everyone has easy access? 

I have been failing for over a week now, and I feel kind of dumb. I have tried many Youtube videos, Reddit (threads such as r/hackintosh), many sites, etc. with no avail, and this is driving me slightly insane. 

Thank you in advance for your time, and original post.

Thanks, 
JK3171

Edit: I forgot to ask as well about your config.plist

**Comment by ishaan26** [comment]
Hi @jk3171 

Unfortunately, due to the lockdown I had to return to my home from my dorm and my predator is in my dorm because my university was closed before the lockdown and I had no idea it will extend this much (I know... I am desperate to get it back but there is no way for me to do so before August as my university won't open before that).

I don't remeber the exact steps as its been over an year since installed hackintosh and therefore cannot make a guide without trying to install it once again as you know... it is not a straightforward process . 

But I would seriously recommend that you use windows, linux or a dual boot of windows and linux because I can tell you, hackintosh on this laptop it is not a great experience and frankly a waste of time! (Wifi doesn't work, nvidia graphics don't work, trackpad geastures don't work, sleep wake doesn't work, battery dies in 30 mins, no control on brightness or fan speed) I have my self uninstalled it long ago because it is just not worth the trouble.

But if you really want it I will be sure to update the readme with a proper guide when I get my hands on the laptop. If you are having a specific problem you can ask me and I will do my best to help you.

The config.plist is available in the repo under the clover folder. (Not the config_hz one but the other one named config.plist) 

I hope you can understand.

Thankyou and stay safe!

**Comment by jk3171** [comment]
> Hi @jk3171 
> 
> Unfortunately, due to the lockdown I had to return to my home from my dorm and my predator is in my dorm because my university was closed before the lockdown and I had no idea it will extend this much (I know... I am desperate to get it back but there is no way for me to do so before August as my university won't open before that).
> 
> I don't remeber the exact steps as its been over an year since installed hackintosh and therefore cannot make a guide without trying to install it once again as you know... it is not a straightforward process . 
> 
> But I would seriously recommend that you use windows, linux or a dual boot of windows and linux because I can tell you, hackintosh on this laptop it is not a great experience and frankly a waste of time! (Wifi doesn't work, nvidia graphics don't work, trackpad geastures don't work, sleep wake doesn't work, battery dies in 30 mins, no control on brightness or fan speed) I have my self uninstalled it long ago because it is just not worth the trouble.
> 
> But if you really want it I will be sure to update the readme with a proper guide when I get my hands on the laptop. If you are having a specific problem you can ask me and I will do my best to help you.
> 
> The config.plist is available in the repo under the clover folder. (Not the config_hz one but the other one named config.plist) 
> 
> I hope you can understand.
> 
> Thankyou and stay safe!

Wow, let me start by thanking you for such a quick and long response. I actually went out, and I figured it all out in the time since. I actually got working/fixed most of the things that didn’t work for you, as well. I will be most likely making a repo with the EFI I used and instructions on how to go about this; I will comment here again, to let you know when it’s done so you can use it for yourself. 

THINGS THAT DON’T WORK:
- 1060 (dGPU)
- HDMI (Attached to the dGPU)
- SD Card Reader (I will be fixing soon, with a kext)

THINGS THAT WORK THAT DIDN’T WORK FOR YOU:
- WiFi (Replace the WiFi card to a DW1560)
- Sleep/Wake
- Battery Lasts Around 4hr on full brightness and under load
- Brightness/Volume Control with the Same Keys (Arrows)

NOTE:
I did not test fan speed, but it seems to be adapting to the load.

Thanks Again!

**Comment by ishaan26** [comment]
Oh wow, that is great! I will surely check out your repo.
Thanks a lot!
